version: '2'
services:
    confdata:
        container_name: confdata
        image: eristoddle/wso2-dev-config
        volumes:
            - /tmp/wso2scripts:/conf/wso2scripts

    # TODO: This is not the final configuration
    wso2postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=wso2user
        volumes:
            - /tmp/wso2scripts/postgres-init:/docker-entrypoint-initdb.d
            - /tmp/postgresql/data:/var/lib/postgresql/data
            - /tmp/wso2scripts/postgres-sql:/tmp/postgres-sql

    # TODO: Custom manually built image
    is:
        image: eristoddle/wso2is_final
        # build:
        #     context: ./conf/wso2is
        hostname: wso2identity
        ports:
            - 9443:9443
            - 9763:9763

    # TODO: Custom manually built image
    esb:
        image: eristoddle/wso2esb_final
        # build:
        #     context: ./conf/wso2esb
        ports:
            - 9444:9444
            - 9764:9764

    greg:
        image: eristoddle/wso2greg_final
        build:
            context: ./conf/wso2greg
        command: -Dsetup
        ports:
            - 9445:9445
            - 9765:9765

    brs:
        image: eristoddle/wso2brs_final
        build:
            context: ./conf/wso2brs
        ports:
            - 9446:9446
            - 9766:9766

    dss:
        image: eristoddle/wso2dss_final
        build:
            context: ./conf/wso2dss
        ports:
            - 9447:9447
            - 9767:9767

    apim:
        image: eristoddle/wso2am_final
        build:
            context: ./conf/wso2am
        ports:
            - 9448:9448
            - 9768:9768

    as:
        image: eristoddle/wso2as_final
        build:
            context: ./conf/wso2as
        ports:
            - 9449:9449
            - 9769:9769
