version: '2'

services:
    confdata:
        # TODO: Temporarily pulling generic config volume from dockerhub to test things. Change this.
        # This the image built from the Dockerfile in this project
        image: eristoddle/wso2-dev-config
        container_name: confdata
        labels:
            io.rancher.container.start_once: 'true'
            io.rancher.container.pull_image: always
        volumes:
            - /opt/wso2am:/conf/wso2am
            - /opt/wso2as:/conf/wso2as
            - /opt/wso2brs:/conf/wso2brs
            - /opt/wso2dss:/conf/wso2dss
            - /opt/wso2esb:/conf/wso2esb
            - /opt/wso2greg:/conf/wso2greg
            - /opt/wso2is:/conf/wso2is
            - /opt/wso2mysql:/conf/wso2mysql
            - /opt/wso2scripts:/conf/wso2scripts
    mysql:
        image: mysql:5.7.10
        environment:
            - MYSQL_ROOT_PASSWORD=password
        depends_on:
            - confdata
        volumes:
            - /opt/wso2scripts/mysql:/docker-entrypoint-initdb.d
            - /opt/wso2mysql/:/etc/mysql/conf.d
            - /var/lib/mysql

    esb:
        image: eristoddle/wso2esb:5.0.0
        ports:
            - 9443:9443
            - 9763:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2esb/repository/conf/datasources/master-datasources.xml:/mnt/wso2esb/repository/conf/datasources/master-datasources.xml
            - /opt/wso2esb/repository/conf/registry.xml:/mnt/wso2esb/repository/conf/registry.xml
            - /opt/wso2esb/repository/conf/security/authenticators.xml:/mnt/wso2esb/repository/conf/security/authenticators.xml

    brs:
        image: eristoddle/wso2esb:5.0.0
        ports:
            - 9444:9443
            - 9764:9763
        depends_on:
            - confdata
        # NOTE: There is no standalone BRS any more. So this is another ESB but uses configs from the /conf/wso2brs folder
        volumes:
            - /opt/wso2brs/repository/conf/datasources/master-datasources.xml:/mnt/wso2esb/repository/conf/datasources/master-datasources.xml
            - /opt/wso2brs/repository/conf/registry.xml:/mnt/wso2esb/repository/conf/registry.xml
            - /opt/wso2brs/repository/conf/security/authenticators.xml:/mnt/wso2esb/repository/conf/security/authenticators.xml

    greg:
        image: eristoddle/wso2greg:5.3.0
        command: -Dsetup
        ports:
            - 9445:9443
            - 9765:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2greg/repository/conf/datasources/master-datasources.xml:/mnt/wso2greg/repository/conf/datasources/master-datasources.xml
            - /opt/wso2greg/repository/conf/security/authenticators.xml:/mnt/wso2greg/repository/conf/security/authenticators.xml
            - /opt/wso2greg/repository/conf/registry.xml:/mnt/wso2greg/repository/conf/registry.xml

    dss:
        image: eristoddle/wso2dss:3.5.1
        ports:
            - 9446:9443
            - 9766:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2dss/repository/conf/datasources/master-datasources.xml:/mnt/wso2dss/repository/conf/datasources/master-datasources.xml
            - /opt/wso2dss/repository/conf/registry.xml:/mnt/wso2dss/repository/conf/registry.xml
            - /opt/wso2dss/repository/conf/security/authenticators.xml:/mnt/wso2dss/repository/conf/security/authenticators.xml

    is:
        image: eristoddle/wso2is:5.2.0
        hostname: wso2identity
        ports:
            - 9447:9443
            - 9767:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2is/repository/conf/datasources/master-datasources.xml:/mnt/wso2is/repository/conf/datasources/master-datasources.xml
            - /opt/wso2is/repository/conf/carbon.xml:/mnt/wso2is/repository/conf/carbon.xml
            - /opt/wso2is/repository/conf/registry.xml:/mnt/wso2is/repository/conf/registry.xml
            - /opt/wso2is/repository/conf/user-mgt.xml:/mnt/wso2is/repository/conf/user-mgt.xml
            - /opt/wso2is/repository/conf/security/sso-idp-config.xml:/mnt/wso2is/repository/conf/security/sso-idp-config.xml

    am:
        image: eristoddle/wso2am:2.0.0
        ports:
            - 9448:9443
            - 9768:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2am/repository/conf/datasources/master-datasources.xml:/mnt/wso2am/repository/conf/datasources/master-datasources.xml
            - /opt/wso2am/repository/conf/registry.xml:/mnt/wso2am/repository/conf/registry.xml
            - /opt/wso2am/repository/conf/security/authenticators.xml:/mnt/wso2am/repository/conf/security/authenticators.xml

    as:
        image: eristoddle/wso2as:5.3.0
        ports:
            - 9449:9443
            - 9769:9763
        depends_on:
            - confdata
        volumes:
            - /opt/wso2as/repository/conf/datasources/master-datasources.xml:/mnt/wso2as/repository/conf/datasources/master-datasources.xml
            - /opt/wso2as/repository/conf/registry.xml:/mnt/wso2as/repository/conf/registry.xml
            - /opt/wso2as/repository/conf/security/authenticators.xml:/mnt/wso2as/repository/conf/security/authenticators.xml
